name: Docker Image UserBack CD
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: "./UserBackend"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.working-directory }}
          file: ${{ env.working-directory }}/UserBackend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/comic-book-library:userbackend