#CI of CICD
name: Vue Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pull_request_test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['./user-front-end', './admin-front-end'] }
    steps:
      - name: Get code in VM
        uses: actions/checkout@v2
      - name: Test project
        working-directory: ${{ matrix.dir }}
        run: |
              npm install
              npm run build
              npm run test:unit