#CI of CICD
name: Asp Webapi users Continuous Integration
on:
  push:
    branches: [ "main" ]
    paths:
    - '**.cs'
    - '**.csproj'
  pull_request:
    branches: [ "main" ]
    paths:
    - '**.cs'
    - '**.csproj'
  workflow_dispatch:
env:
  DOTNET_VERSION: '6.0.401'
jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install, Build and Test
        working-directory: ./UserBackend
        run: |
              dotnet restore
              dotnet build --configuration Release --no-restore
              dotnet test --no-restore --verbosity normal